
CREATE TABLE USERS(
  ID NUMBER,
    CONSTRAINT USER_PK PRIMARY KEY(ID),
  USER_NAME NVARCHAR2(100) NOT NULL,
  PASSWORD NVARCHAR2(50) NOT NULL,
  COUNTRY NVARCHAR2(50),
  USER_TYPE NVARCHAR2(20)
);

CREATE SEQUENCE USERS_PK_SEQ MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;