    CREATE TABLE FILES (
    ID NUMBER,
    CONSTRAINT FILE_PK PRIMARY KEY(ID),
    NAME NVARCHAR2(50) NOT NULL,
    FORMAT NVARCHAR2(20) NOT NULL,
    FILE_SIZE NUMBER CHECK(FILE_SIZE > 0),
    STORAGE_ID NUMBER NOT NULL,
    CONSTRAINT STORAGE_FK FOREIGN KEY(STORAGE_ID) REFERENCES STORAGE(ID)
);