CREATE TABLE ROOM(
ID NUMBER,
CONSTRAINT ROOM_PK PRIMARY KEY(ROOM_ID),
NUMBER_OF_GUESTS NUMBER(20),
PRICE NUMBER (10,2) NOT NULL,
BREAKFAST_INCLUDED NUMBER(1) NOT NULL,
CHECK (BREAKFAST_INCLUDED BETWEEN 0 AND 1),
PETS_ALLOWED NUMBER NOT NULL,
CHECK (PETS_ALLOWED BETWEEN 0 AND 1),
DATE_AVAILABLE_FROM TIMESTAMP,
HOTEL_ID NUMBER NOT NULL,
CONSTRAINT HOTEL_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTEL(ID)
);


CREATE TABLE HOTEL(
ID NUMBER NOT NULL,
CONSTRAINT HOTEL_ID PRIMARY KEY(ID),
NAME NVARCHAR2(50) NOT NULL,
COUNTRY NVARCHAR2(50) NOT NULL,
CITY NVARCHAR2(50) NOT NULL,
STREET NVARCHAR2(50) NOT NULL
);


CREATE SEQUENCE HOTEL_SEQ
MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE ROOM_SEQ
MINVALUE 1
MAXVALUE 10000
INCREMENT BY 1
START WITH 1;



CREATE TABLE ORDERS(
  ID NUMBER,
    CONSTRAINT ORDER_PK PRIMARY KEY(ID),
  USER_ID NUMBER,
    CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
  ROOM_ID NUMBER,
    CONSTRAINT ROOM_FK FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ID),
  DATE_FROM TIMESTAMP NOT NULL,
  DATE_TO TIMESTAMP NOT NULL,
  MONEY_PAID NUMERIC(38,2) CHECK(MONEY_PAID > 0)
);

CREATE SEQUENCE ORDER_PK_SEQ
MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;



CREATE TABLE USERS(
  ID NUMBER,
    CONSTRAINT USER_PK PRIMARY KEY(ID),
  USER_NAME NVARCHAR2(100) NOT NULL,
  PASSWORD NVARCHAR2(50) NOT NULL,
  COUNTRY NVARCHAR2(50),
  USER_TYPE NVARCHAR2(20)
);

CREATE SEQUENCE USERS_PK_SEQ MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;