
CREATE TABLE ORDERS(
  ID NUMBER,
    CONSTRAINT ORDER_PK PRIMARY KEY(ID),
  USER_ID NUMBER,
    CONSTRAINT USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
  ROOM_ID NUMBER,
    CONSTRAINT ROOM_FK FOREIGN KEY(ROOM_ID) REFERENCES ROOM(ID),
  DATE_FROM TIMESTAMP NOT NULL,
  DATE_TO TIMESTAMP NOT NULL,
  MONEY_PAID NUMERIC(38,2) CHECK(MONEY_PAID > 0)
);

CREATE SEQUENCE ORDER_PK_SEQ
MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;

