CREATE TABLE HOTEL(
ID NUMBER NOT NULL,
CONSTRAINT HOTEL_ID PRIMARY KEY(ID),
NAME NVARCHAR2(50) NOT NULL,
COUNTRY NVARCHAR2(50) NOT NULL,
CITY NVARCHAR2(50) NOT NULL,
STREET NVARCHAR2(50) NOT NULL
);


CREATE SEQUENCE HOTEL_SEQ
MINVALUE 1
MAXVALUE 1000
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE ROOM_SEQ
MINVALUE 1
MAXVALUE 10000
INCREMENT BY 1
START WITH 1;